---
# Tasks specific for RedHat systems

- name: "RedHat | Set some facts Zabbix"
  set_fact:
    apache_log: httpd
    datafiles_path: "/usr/share/doc/zabbix-proxy-{{ database_type }}-{{ zabbix_version }}*/create"
  when: zabbix_version != 3.0

- name: "RedHat | Set facts for Zabbix 3.0"
  set_fact:
    apache_log: httpd
    datafiles_path: "/usr/share/doc/zabbix-proxy-{{ database_type }}-{{ zabbix_version }}*"
  when: zabbix_version == 3.0

- name: "RedHat | Install basic repo file"
  template: src=rhel.repo.j2
            dest=/etc/yum.repos.d/zabbix.repo
            owner=root
            group=root
            mode=0644
  when: zabbix_repo

- name: "RedHat | Installing zabbix-proxy-database_type"
  yum:  pkg=zabbix-proxy-{{ database_type }}
        state=present

- name: "RedHat | Install Ansible module dependencies"
  yum: name=python-psycopg2
       state=present
  when: zabbix_database_creation
  tags:
    - zabbix-proxy
    - init

- name: "RedHat | Install Mysql Client package RHEL7"
  yum: name={{ item }}
       state=installed
  with_items:
    - mariadb
    - MySQL-python
  when: database_type == 'mysql' and ansible_distribution_major_version == '7'
  tags:
    - zabbix-proxy
    - init

- name: "RedHat | Install Mysql Client package RHEL5 - 6"
  yum: name={{ item }}
       state=present
  with_items:
    - mysql
    - MySQL-python
  when: database_type == 'mysql' and ansible_distribution_major_version != '7'
  tags:
    - zabbix-proxy
    - init
    - database

- name: "RedHat | Install PostgreSQL client package"
  yum: name=postgresql
       state=latest
  when: database_type == 'pgsql'
  tags:
    - zabbix-proxy
    - init
    - database
